### ISSUE TITLE
Master werkt niet meer na `npm start`

### ISSUE THREAD

**Issue by HeinPauwelyn** [WatchFriends/Web#93]
Master werkt niet meer na `npm start`. Zie error:

```
> watchfriends@0.0.0 start D:\Documenten\WatchFriends\Backend
> ng serve --proxy-config proxy.conf.json

** NG Live Development Server is running on http://localhost:4200. **
 10% building modules 2/2 modules 0 active[HPM] Proxy created: /api  ->  http://localhost:3000
Error: Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol AppModule in D:/Documenten/WatchFriends/Backend/frontend/app/app.module.ts, resolving symbol AppModule in D:/Documenten/WatchFriends/Backend/frontend/app/app.module.ts
    at simplifyInContext (D:\Documenten\WatchFriends\Backend\node_modules\@angular\compiler-cli\src\static_reflector.js:475:23)
    at StaticReflector.simplify (D:\Documenten\WatchFriends\Backend\node_modules\@angular\compiler-cli\src\static_reflector.js:478:22)
    at StaticReflector.annotations (D:\Documenten\WatchFriends\Backend\node_modules\@angular\compiler-cli\src\static_reflector.js:60:36)
    at AotPlugin.getNgModuleMetadata (D:\Documenten\WatchFriends\Backend\node_modules\@ngtools\webpack\src\plugin.js:330:41)
    at AotPlugin._processNgModule (D:\Documenten\WatchFriends\Backend\node_modules\@ngtools\webpack\src\plugin.js:271:42)
    at D:\Documenten\WatchFriends\Backend\node_modules\@ngtools\webpack\src\plugin.js:242:39
    at process._tickCallback (internal/process/next_tick.js:103:7)
 70% building modules 619/619 modules 0 active)
```

**Comment by mickverm** [comment]
had ik ook, node_modules verwijderen en dan npm install uitvoeren
