### ISSUE TITLE
Hoe krijg ik api op backend

### ISSUE THREAD

**Issue by HeinPauwelyn** [WatchFriends/Web#95]
hoe kan ik op de backend de API ophalen? 

- Als ik <kbd>F5</kbd> druk krijg ik een error
- Bij `npm start` is de pagina niet beschikbaar op [localhost:3000/data](#) en [localhost:4200/data](#) krijg ik opnieuw de home pagina.
- Bij http://localhost:4200/api/series/45 krijg ik volgende error:

   > Error occured while trying to proxy to: localhost:4200/api/series/45

**Comment by JasperDeSutter** [comment]
Welke error krijg je bij F5?

**Comment by HeinPauwelyn** [comment]
> Cannot read property `facebook` of undefined 

op [`backend/data/passport.js` lijn 87](https://github.com/WatchFriends/Web/blob/master/backend/data/passport.js#L87)

Stacktrace:

```none
"TypeError: Cannot read property 'facebook' of undefined
    at module.exports.config (d:\\Documenten\\WatchFriends\\Backend\\backend\\data\\passport.js:87:30)
    at Object.<anonymous> (d:\\Documenten\\WatchFriends\\Backend\\backend\\server.js:15:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Timeout.Module.runMain [as _onTimeout] (module.js:604:10)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)"
```

**Comment by JasperDeSutter** [comment]
Pas jouw config.json aan zoals config.fakeson. vergeet niet iets in de lege strings te steken.

**Comment by HeinPauwelyn** [comment]
Kan er iemand eens een volledige config file op slack zetten? merci.
